export const fallbackCategoryOptions = [
  { label: 'Концерти', value: '10' },
  { label: 'Класическа музика', value: '11' },
  { label: 'Клубна музика', value: '12' },
  { label: 'Рок и Метъл', value: '13' },
  { label: 'Поп и Джаз', value: '14' },
  { label: 'Народна музика', value: '15' },
  { label: 'Опера и Балет', value: '16' },
  { label: 'Комедия и Stand-up', value: '17' },
  { label: 'Танц и Шоу', value: '18' },
  { label: 'Работилници и Занаятчийство', value: '19' },
  { label: 'Спорт', value: '20' },
  { label: 'Семейни събития', value: '21' },
  { label: 'Градски събития', value: '22' },
  { label: 'Здраве и Уелнес', value: '23' },
  { label: 'Храна и Напитки', value: '24' },
  { label: 'Пътувания и Приключения', value: '25' },
  { label: 'Технологии и Бизнес', value: '26' },
  { label: 'Общество и Каузи', value: '27' },
  { label: 'Мода и Дизайн', value: '28' },
  { label: 'Обучения и Кариера', value: '29' },
  { label: 'Театър', value: '30' },
  { label: 'Детски спектакли', value: '31' },
  { label: 'Българска музика', value: '32' },
  { label: 'Електронна музика', value: '33' },
  { label: 'Хип-хоп и R&B', value: '34' },
  { label: 'Фолклор и Традиции', value: '35' },
  { label: 'Изложби и Галерии', value: '36' },
  { label: 'Мюзикъли и Шоу', value: '37' },
  { label: 'Кино', value: '40' },
  { label: 'Фестивали', value: '50' },
  { label: 'Изложби', value: '60' },
  { label: 'Литература', value: '70' },
  { label: 'Семинари и Лекции', value: '80' },
  { label: 'Други', value: '90' },
];