-- Seed the initial public events used by the app UI.

insert into public.events (
  id_event,
  name_event,
  name_artist,
  place_event,
  id_event_category,
  id_user,
  id_region,
  start_date,
  start_hour,
  end_date,
  end_hour,
  picture,
  description,
  is_free,
  price_info,
  ticket_url
) values
  (
    1,
    'Лятна рок вечер',
    'The Horizon Band',
    'Летен театър',
    10,
    2,
    23,
    current_date + 14,
    time '19:30',
    current_date + 14,
    time '22:30',
    'events/1_2.jpg',
    'Рок концерт под открито небе с авторски парчета, гост-музиканти и любими класики за феновете на живата сцена.',
    false,
    'От 25 лв.',
    null
  ),
  (
    2,
    'Маратон Варна 2026',
    'Организационен екип',
    'Морска градина',
    20,
    3,
    3,
    current_date + 21,
    time '08:00',
    current_date + 21,
    time '13:00',
    'events/2_3.jpg',
    'Градско спортно събитие за аматьори и професионалисти с различни дистанции, медали и морска атмосфера.',
    true,
    null,
    null
  ),
  (
    3,
    'Театрална премиера „Сцената диша“',
    'Драматичен театър Пловдив',
    'Основна сцена',
    30,
    4,
    16,
    current_date + 30,
    time '19:00',
    current_date + 30,
    time '21:20',
    'events/3_4.jpg',
    'Премиерен спектакъл с модерна драматургия, силна актьорска игра и специално сценично оформление за публиката.',
    false,
    'От 20 лв.',
    'https://example.com/tickets/3'
  ),
  (
    4,
    'Кино под звездите Бургас',
    'Open Air Cinema',
    'Лятно кино',
    40,
    5,
    2,
    current_date + 37,
    time '20:30',
    current_date + 37,
    time '23:00',
    'events/4_5.jpg',
    'Лятна прожекция на открито с удобни места, тематична атмосфера и подбрана програма от съвременно кино.',
    true,
    null,
    null
  ),
  (
    5,
    'Фестивал на занаятите',
    'Craft & Folk BG',
    'Централен площад',
    50,
    2,
    4,
    current_date + 45,
    time '10:00',
    current_date + 47,
    time '20:00',
    'events/5_2.jpg',
    'Тридневен градски фестивал с работилници, местни производители, сцена за музика и кулинарни щандове.',
    true,
    null,
    null
  )
on conflict (id_event) do update set
  name_event = excluded.name_event,
  name_artist = excluded.name_artist,
  place_event = excluded.place_event,
  id_event_category = excluded.id_event_category,
  id_user = excluded.id_user,
  id_region = excluded.id_region,
  start_date = excluded.start_date,
  start_hour = excluded.start_hour,
  end_date = excluded.end_date,
  end_hour = excluded.end_hour,
  picture = excluded.picture,
  description = excluded.description,
  is_free = excluded.is_free,
  price_info = excluded.price_info,
  ticket_url = excluded.ticket_url;